### ISSUE TITLE
Reevaluate newline style/number of newlines

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/contributing#3]
Looking at the last example in https://github.com/ComputationalRadiationPhysics/contributing/blob/master/codingGuideLines/cpp.md#17-template-class--struct-and-type-definitions (under the comment `// template function specialization`) I think the number of newlines should be substantially reduced as it destroys the context. If you scroll over something like that you cannot tell if this is a class, method or where anything really starts or ends. Especially with the C++11 trailing return type that adds an extra `>` in the `->` making it much harder to distinguish method name, signature, return type and body.

It would help to put short template argument lists on the same line:

    // old
    foo<
        int,
        float
    >

    // new
    foo< int, float >

**Comment by mxmlnkn** [comment]
+1

**Comment by ax3l** [comment]
As you linked it correctly, the idea is to have the **declaration** as readable as possible since one shares that with other developers. The example you provided is *in-code* where we would not necessary need/enforce that.

For declarations (function headers / class headers / ...) this usually looks more like this:
```C++
template<
    someNamespace::SomeClass,
    typename someOtherNamespace::SomeOtherClass::SomePublicTypedef
>
class { /* ... */ };
```

**Comment by psychocoderHPC** [comment]
I will close this request, @ax3l added a good example and description for the chosen rule
