### ISSUE TITLE
class or typename to type template parameters

### ISSUE THREAD

**Issue by slizzered** [ComputationalRadiationPhysics/contributing#5]
Looking at the examples [here](https://github.com/ComputationalRadiationPhysics/contributing/blob/master/codingGuideLines/cpp.md#17-template-class--struct-and-type-definitions):  
```c++
template<
    typename T_Foo,
    class T_FooBar
>
```

I find the mixed use of `typename` and `class` not really intutive

**Comment by psychocoderHPC** [comment]
I don't know what is the best. I found [this](http://stackoverflow.com/questions/213121/use-class-or-typename-for-template-parameters) were they discuss if `typename` or `class` should be used.

The discussion shows that C++14 needs `class` at some points which should be fixed in `C++17`. I am confused.

**Comment by slizzered** [comment]
From what I gathered (from your link and also [this](http://stackoverflow.com/questions/2023977/c-difference-of-keywords-typename-and-class-in-templates)), It seems that `typename` can not be used in template-template scenarios.
This is not only happening in *C++14*, but also previous versions (including C++98, if I'm correct). Current compilers (*gcc5*, *clang3.5*) have resolved this problem.

I would suggest to use `typename` wherever possible (the cases of template-template parameters are rather rare, I guess)

No matter how it turns out to be, we should change the quoted example to avoid confusion
